#!/usr/bin/env python
# encoding: utf-8

"""
-------------------------------------------------
   File Name：     testUI
   Description :
   Author :        Meiyo
   date：          2019/10/11 10:39
-------------------------------------------------
   Change Activity:
                   2019/10/11:
------------------------------------------------- 
"""
__author__ = 'Meiyo'

import unittest
from testcases import test_kaimaiCashierForAndroid
from HTMLTestRunner import HTMLTestRunner


if __name__ == '__main__':
    suite = unittest.TestSuite()
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_kaimaiCashierForAndroid.CashierForAndroidCase))
    suite.addTests(unittest.TestLoader().loadTestsFromModule(test_kaimaiCashierForAndroid))
    # result = unittest.TextTestRunner(verbosity=0).run(suite)

    with open('HTMLReport.html', 'w', encoding='utf-8') as f:
        runner = HTMLTestRunner(stream=f,
                                title='UI Test For Cashier Of Kaimai',
                                description='generated by HTMLTestRunner.',
                                verbosity=2,
                                retry=2
                                )
        runner.run(suite)

